services:
  mariadb:
    image: mariadb:latest
    container_name: foodapp.db
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql # Persistent data volume
      - ./db_init:/docker-entrypoint-initdb.d # MariaDB runs all .sql and .sh files in this directory on the first startup
    ports:
      - "3306:3306" # Expose so the DB can be accessed from the local machine in dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2 # Same as Python lib version
    container_name: foodapp.elasticsearch
    restart: always
    environment:
      - discovery.type=single-node # Set to single-node setup
      - xpack.security.enabled=false # Disable security
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Set memory limits for Elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200" # Access Elasticsearch from local machine so we can push data to it
      - "9300:9300"

  api:
    build: ./api
    container_name: foodapp.api
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - elasticsearch
    volumes:
      - ./api:/app # Mount for development - changes propagate automatically. Don't use --watch due to bugs w/ hot reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development # Use 'development' for dev, 'production' for prod
    container_name: foodapp.frontend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
    command: npm run dev
    depends_on:
      - api

volumes:
  mariadb_data:
  elasticsearch_data:
