services:
  mariadb:
    ports: [] # Don't expose port to host machine. Services in Dockerfile can still access MariaDB though
    networks:
      - internal # Manually specify default network since we specified networks for api and frontend

  elasticsearch:
    ports: [] # See MariaDB ports comment
    networks:
      - internal

  api:
    ports:
      - "3041:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers
    networks:
      - internal
      - nginx-proxy

  frontend:
    ports:
      - "3040:3000"
    build:
      target: production
    command: npm run start
    networks:
      - nginx-proxy

networks:
  internal:
    driver: bridge
  nginx-proxy:
    name: nginx-proxy # Used for reverse proxy across multiple services
    external: true
