services:
  mariadb:
    ports: [] # Don't expose port to host machine. Services in Dockerfile can still access MariaDB though

  elasticsearch:
    ports: [] # See MariaDB ports comment

  api:
    ports:
      - "3041:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers

  frontend:
    ports:
      - "3040:3000"
    build:
      target: production
    environment:
      - NODE_ENV=production
    command: npm run start
